---
title: "Scratchpad - Yeshaya"
output : html_document
---

This document contains all the rough work involved in the cleaning up of data as well as some experimental graphs and work. 
```{r read-file}

```


```{r view-terms}
unique(Tidy_Term$Year)

Tidy_Term %>% 
  arrange(Year)
```

```{r check-further-terms}
Tidy_Term %>%
  arrange(Year) %>%
  slice(1000:1628)
```



```{r clean-terms}
Tidy_Time <- Tidy_Term %>% 
mutate(Year = case_when(
  Year %in% c("1970") ~ "1970",
  Year %in% c("1973", "1973, 1974, 1975") ~ "1973",
  Year %in% c("1974") ~ "1974",
  Year %in% c("1975", "1974, 1975") ~ "1975",
  Year %in% c("1976") ~"1976",
  Year %in% c("1977", "1977, 1975, 1972") ~ "1977",
  Year %in% c("1978", "1977,1978") ~ "1978",
  Year %in% c("1979","1976-79") ~ "1979",
  Year %in% c("1980", "1978, 1979, 1980", "1979 and 1980") ~ "1980",
  Year %in% c("1981") ~ "1981",
  Year %in% c("1982", "1981, 1982") ~ "1982",
  Year %in% c("1983","1981-1983") ~ "1983",
  Year %in% c("1984") ~ "1984",
  Year %in% c("1985", "1984, 1985") ~ "1985",
  Year %in% c("1986", "1985, 1986") ~ "1986",
  Year %in% c("1987") ~"1987",
  Year %in% c("1988", "1987, 1988") ~ "1988",
  Year %in% c("1989") ~ "1989",
  Year %in% c("1990") ~ "1990",
  Year %in% c("1991") ~ "1991",
  Year %in% c("1992") ~ "1992",
  Year %in% c("1993", "1987-1993") ~ "1993",
  Year %in% c("1994") ~ "1994",
  Year %in% c("1995") ~ "1995",
  Year %in% c("1996", "1994, 1995, 1996", "1995, 1996") ~ "1996",
  Year %in% c("1997") ~ "1997",
  Year %in% c("1998", "	1997, 1998") ~ "1998",
  Year %in% c("1999", "1997, 1998, 1999", "1998/1999") ~ "1999",
  Year %in% c("2000") ~ "2000",
  Year %in% c("2001") ~ "2001",
  Year %in% c("2002", "2001, 2002") ~ "2002",
  Year %in% c("2003") ~ "2003",
  Year %in% c("2004") ~"2004",
  Year %in% c("2005", "2003, 2004, 2005") ~ "2005",
  Year %in% c("2006") ~ "2006",
  Year %in% c("2007", "2006, 2007") ~ "2007",
  Year %in% c("2008", "1996-2008") ~ "2008",
  Year %in% c("2009","2002 - 2009") ~ "2009",
  Year %in% c("2010", "2009-2010") ~ "2010",
  Year %in% c("2011","	2009-2011") ~ "2011",
  Year %in% c("2012") ~ "2012",
  Year %in% c("2013") ~ "2013",
  Year %in% c("2014", "	2013-2014") ~ "2014",
  Year %in% c("2015", "2014-15") ~ "2015",
  Year %in% c("2016", "	2015, 2016") ~ "2016",
  Year %in% c("2017", "	2015, 2016, 2017") ~ "2017",
  Year %in% c("2018") ~ "2018",
  Year %in% c("2019") ~ "2019",
  Year %in% c("2020") ~ "2020",
  Year %in% c("2021") ~ "2021",
  Year %in% c("2022") ~ "2022",
  Year %in% c("2023") ~ "2023"
))
```


```{r recheck-terms}
unique(Tidy_Time$Year)
```
```{r recheck-further}
Tidy_Time %>% 
arrange(Year) %>% 
  slice(1000:1628)
```

```{r double-check}
Tidy_Time %>% 
  group_by(Year) %>%
  summarise(count = n())
```


```{r further-cleaning}
# additional cleaning 

Tidy_Mapped_Clean <- Tidy_Mapped %>% 
  filter(Year != "0") %>% 
   filter(!is.na(Term), !is.na(Location), !is.na(Longitude), !is.na(Latitude))
```

```{r checking-data}
# checking
Test_Cleaning <- Tidy_Mapped_Clean %>% 
  select(Term, Location, Latitude, Longitude, Year)

  vis_miss(Test_Cleaning)

```
```{r visualisation}
Test_Cleaning <- Tidy_Mapped_Clean %>% 
  select(Term, Location, Latitude, Longitude, Year)

  vis_dat(Test_Cleaning)

```
```{r saving-data}
#write.csv(Tidy_Mapped_Clean, "Tidy_Mapped_Clean.csv", row.names = FALSE)
```

```{r chat-gpt-geocoding}
# Load necessary libraries
library(tidyverse)
library(tidygeocoder)  # For geocoding with Nominatim API

# Load the data
#experiment <- read.csv("/cloud/project/data/Tidy_Time.csv")

# Function to get coordinates based on the location
#get_coordinates <- function(location) {
  #if (is.na(location)) {
    #return(c(NA, NA)) # Leave as NaN if location is NaN
  #}
  
  # Handle multiple entries by taking the second one if separated by '/'
  #if (grepl("/", location)) {
    #location <- str_split(location, "/")[[1]][2] %>% str_trim()
  #}
  
  # Try geocoding with town/city
  #result <- tryCatch(
    #{
      #Sys.sleep(1)  # Add delay of 1 second between requests
      #geocode(location, method = 'osm', lat = Latitude, long = Longitude, limit = 1)
   # },
    #error = function(e) tibble(Latitude = NA, Longitude = NA) # In case of failure
  #)
  
  # Fallback to state or country if exact town/city is not found
  #if (is.na(result$Latitude)) {
    #if (grepl(",", location)) {
      #fallback_location <- str_split(location, ",")[[1]][2] %>% str_trim()
      #result <- tryCatch(
        #{
         # Sys.sleep(1)  # Add delay for fallback geocoding attempt
          #geocode(fallback_location, method = 'osm', lat = Latitude, long = Longitude, limit = 1)
        #},
        #error = function(e) tibble(Latitude = NA, Longitude = NA)
      #)
    #}
  #}
  
  # Default to Bar Harbor, ME coordinates if both fail
  #if (is.na(result$Latitude)) {
    #result <- tibble(Latitude = 44.387611, Longitude = -68.203911) # Bar Harbor, ME coordinates
  #}
  
  #return(c(result$Latitude, result$Longitude))
#}

# Apply the function to fill in missing Latitude and Longitude
#experiment <- experiment %>%
  #mutate(
    #coords = map(Location, get_coordinates),
    #Latitude = ifelse(is.na(Latitude), map_dbl(coords, 1), Latitude),
    #Longitude = ifelse(is.na(Longitude), map_dbl(coords, 2), Longitude)
  #) %>%
  #select(-coords) # Drop intermediate column

# Save the updated dataset
# write.csv(data, "Tidy_Time_Filled.csv", row.names = FALSE)
```

