Jordan Speers 
Tidying Term Data 

```{r load-stuffs}
library(tidyverse)
library(broom)
library(leaflet)
library(colorspace)
library(sf)
#install.packages("visdat")
library(visdat)
library(naniar)
library(UpSetR)

Internship_Data_Untidy <- read.csv("/cloud/project/data/Internship_Data_Untidy.csv")

```

```{r see-unique-term-entries}
unique(Internship_Data_Untidy$Term)
```

```{r filtering-the-bs}
Jordans_half_untidy_data <- Internship_Data_Untidy %>% 
filter(!Term %in% c("NA", "Not Stated", "-", "", "NA ", "All Year", "n/a", "Year", "Year-round", "N/A", "Previous Work Experience", "Nine Months", "Prior Fulfillment")) %>% 
mutate(Term = str_squish(Term))
```

```{r}
unique(Jordans_half_untidy_data$Term)
```


```{r filtering-for-term}
Tidy_Term <- Jordans_half_untidy_data %>% 
mutate(Term = case_when(
  Term %in% c("Fall", "Winter, Spring, Fall", "Winter, Fall", "Summer-Fall", "Spring, Fall", "Summer/Fall", "Summer, Fall", "Spring, Summer, Fall", "Summer,Fall", "Winter+Fall") ~ "Fall",
  Term %in% c("Winter", "Winter, Fall, Winter", "Fall/Winter", "December-December", "Summer, Fall, Winter", "Fall-Winter", "Fall, Winter", "Summer-Winter") ~ "Winter",
  Term %in% c("Spring", "Fall, Winter, Spring", "spring", "Winter, Spring", "Winter-Spring", "Novermber-Spring", "Summer, Spring, Spring") ~ "Spring",
  Term %in% c("Summer", "Fall, Summer", "August", "Winter-Summer", "Winter, Spring, Summer", "Winter, Summer", "Spring, Summer", "Fall+Summer", "Spring/Summer", "Fall, Winter, Spring, Summer", "Summe", "Summer 2011") ~ "Summer"
))
```

```{r }
Tidy_Term %>% 
  group_by(Term) %>%
  summarise(count = n())
```
```{r year-shit}
unique(Tidy_Term$Year)
```

```{r clean-location-data}
Tidy_Term <- Tidy_Term %>% 
mutate(Location = str_squish(Location))
```

```{r}
Tidy_Time %>% 
ggplot(aes(x = Year,
    fill = Term)) +
 geom_bar(position = "fill") +
  scale_fill_viridis_d()
```
```{r}
Tidy_Mapped %>% 
  filter(Year > 0) %>% 
ggplot(aes(x = Year)) + 
  geom_histogram(binwidth = 1)
```


```{r map-attempt}
summary(Tidy_Time)
```

```{r}
Missing_data <- Tidy_Time %>% 
  select(Term, Location, Latitude, Longitude)

  vis_dat(Missing_data)
```
```{r}
vis_miss(Missing_data)
```

```{r}
Missing_data <- Tidy_Mapped %>% 
  select(Term, Location, Latitude, Longitude)

  vis_dat(Missing_data)
```
```{r}
Missing_data <- Tidy_Mapped %>% 
  select(Term, Location, Latitude, Longitude, Internship.Site, Title..if.applicable., Year)

  vis_miss(Missing_data)
```


```{r squishy-squish}
Tidy_Mapped_Clean %>% 
mutate(Internship.Site = str_squish(Internship.Site)) %>% 
unique(Internship.Site)
```


